### ISSUE TITLE
"Run tests" button not working

### ISSUE THREAD

**Issue by qleguennec** [manadart/NUnitLite.MonoDroid#12]
Hi, I'm trying to run tests on an android device (I tested many devices), but when i touch the "Run tests" button on the screen, nothing happens. The screenshots on your readme don't exactly match the application I'm using, but I don't know either how to remove that bug or where to ask.

[Screenshot](http://postimg.org/image/p2tupv4ev/)

EDIT: I'm working on API 18.
EDIT2: bug resolved by deleting/recreating the project.

**Comment by manadart** [comment]
Hi there,

First off, apologies for the tardiness of this reply; I've been tied up with family/work/travel.

Glad to see that you've resolved the issue. This project is overdue for some attention, which I will endeavor to give it shortly. The old runner will probably be removed and I'll likely move to a new NUnitLite version.

All the best,
Joe
