### ISSUE TITLE
The TestRunner crashes if you tab on a TestCaseName while it is running

### ISSUE THREAD

**Issue by has-taiar** [manadart/NUnitLite.MonoDroid#3]
For test cases that takes a little long time, if you tab on the testCaseName while it is running the applicaiton crashes. 
Also, if it takes long time, the application is not producing any notification to tell the user to wait while running the tests. 

I have forked the code and put a fix for it. The fix works in my env, hope you can commit it. 
Other than that, Thanks heaps for the effort, it is a nice framework.

**Comment by manadart** [comment]
Thanks for this. Can you send a pull request?

**Comment by has-taiar** [comment]
Hi there, 
Thanks for that, but I do not see any option for pull requests. 
I forked your code and fixed the issues. 
Happy to fix them in your code if you tell me how to get a pull request. 

Cheers
Has

**Comment by manadart** [comment]
To the right of the the repository name ("has-taiar / NUnitLite.MonoDroid"), there's a "Pull Request" button.
Right next to the Watch/Unwatch button.

**Comment by manadart** [comment]
PR in https://github.com/SpiritMachine/NUnitLite.MonoDroid/pull/4
